workflows:
  android_build:
    name: Build Android app
    triggers:
      - event: push
        branch: main
    environment:
      vars:
        ANDROID_VERSION: "stable"
    # Aquí van las acciones directamente sin "actions"
    actions:
      - install_dependencies
      - build_android:
          build_type: release
          keystore:
            file: $CM_KEYSTORE_FILE   # Ruta al archivo keystore subida a Codemagic
            password: $CM_KEYSTORE_PASSWORD
            alias: $CM_KEY_ALIAS
            key_password: $CM_KEY_PASSWORD
      - upload_to_play_store  # Subir automáticamente a Google Play
