workflows:
  android:
    name: Build Android App
    source: main  # Nombre de la rama que deseas usar, cambia si es necesario
    actions:
      - action: build
        build_type: release
        keystore:
          file: $CM_KEYSTORE_FILE  # Ruta al archivo keystore subido a Codemagic
          password: $CM_KEYSTORE_PASSWORD
          alias: $CM_KEY_ALIAS
          key_password: $CM_KEY_PASSWORD
      - action: upload_to_play_store  # Solo si deseas subirlo a Google Play
