workflows:
  android_build:
    name: Build Android app
    platform: android
    triggers:
      - event: push
        branch: main
    environment:
      vars:
        ANDROID_VERSION: "stable"
    actions:
      - action: install_dependencies
      - action: build_android
        build_type: release
        keystore:
          file: $CM_KEYSTORE_FILE       # Ruta al archivo keystore subida a Codemagic
          password: $CM_KEYSTORE_PASSWORD
          alias: $CM_KEY_ALIAS
          key_password: $CM_KEY_PASSWORD
      - action: upload_to_play_store  # Si deseas subirlo automáticamente a Google Play
